specificationVersion: '2022-09-01'
parameters:
- name: AdaptorWheels
  type: PATH
  objectType: DIRECTORY
  dataFlow: IN
  description: A directory that contains wheels for openjobio, deadline, and deadline-nuke.
environment:
  name: OverrideNukeAdaptor
  description: >
    Replaces the default NukeAdaptor in the environment's PATH with one from the
    AdaptorWheels parameter.
  script:
    actions:
      onEnter:
        command: '{{ Env.File.Enter }}'
    embeddedFiles:
    - name: Enter
      filename: nuke-adaptor-enter.sh
      type: TEXT
      runnable: true
      data: |
        #!/bin/env bash

        set -euo pipefail

        echo "The adaptor wheels that are attached to the job:"
        ls {{Param.AdaptorWheels}}/
        echo ""

        # Assert that the `python3` command is Nuke's python
        which python3 | grep -q -i nuke

        # Remove some packages that might have been installed
        echo "Uninstalling adaptor packages that may be in the Nuke installation"
        python3 -m pip uninstall deadline-nuke || true
        python3 -m pip uninstall deadline_nuke || true
        python3 -m pip uninstall deadline || true
        python3 -m pip uninstall openjobio || true
        echo ""

        # Create a venv and activate it in this environment
        echo "Creating Python venv for the NukeAdaptor command"
        /usr/local/bin/python3 -m venv '{{Session.WorkingDirectory}}/venv'
        {{Env.File.InitialVars}}
        . '{{Session.WorkingDirectory}}/venv/bin/activate'
        {{Env.File.CaptureVars}}
        echo ""

        echo "Installing adaptor into the venv"
        pip install {{Param.AdaptorWheels}}/openjobio*.whl
        pip install {{Param.AdaptorWheels}}/deadline*.whl
        echo ""

        if [ ! -f '{{Session.WorkingDirectory}}/venv/bin/NukeAdaptor' ]; then
          echo "The Nuke Adaptor was not installed as expected."
          exit 1
        fi
    - name: InitialVars
      filename: initial-vars
      type: TEXT
      runnable: true
      data: |
        #!/usr/bin/env python3
        import os, json
        envfile = "{{Session.WorkingDirectory}}/.envInitial"
        with open(envfile, "w", encoding="utf8") as f:
            json.dump(dict(os.environ), f)
    - name: CaptureVars
      filename: capture-vars
      type: TEXT
      runnable: true
      data: |
        #!/usr/bin/env python3
        import os, json, sys
        envfile = "{{Session.WorkingDirectory}}/.envInitial"
        if os.path.isfile(envfile):
            with open(envfile, "r", encoding="utf8") as f:
                before = json.load(f)
        else:
            print("No initial environment found, must run Env.File.CaptureVars script first")
            sys.exit(1)
        after = dict(os.environ)

        put = {k: v for k, v in after.items() if v != before.get(k)}
        delete = {k for k in before if k not in after}

        for k, v in put.items():
            print(f"updating {k}={v}")
            print(f"openjobio_env: {k}={v}")
        for k in delete:
            print(f"openjobio_unset_env: {k}")
